#!/bin/bash

echo
grep PRODUCT_VERSION /etc/zce.rc | sed -E 's|^\s*PRODUCT_VERSION\s*=\s*|Zend Server Version: |'
echo "Active PHP Version: $(/usr/local/zend/bin/php -r 'echo PHP_VERSION;')"
echo
awk '{print "Zend Server UI Admin Password: "$0}' /var/zs-xchange/ui_admin_pw
awk '{print "Zend Server WebAPI User: docker\nZend Server WebAPI Key: "$0}' /var/zs-xchange/web_api_secret
echo
/usr/local/zend/bin/zendctl.sh status
echo
